# Tests PRs on multiple operating systems and Java versions

name: OptaPlanner CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  os-java:
    name: OS x Java
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.java-version }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Print env
        run: |
          printenv
      - name: Print GitHub event action
        run: |
          echo "${{ github.event_name }}"
      - name: Set FLOW_TYPE to pull-request
        if: github.event_name == 'pull_request'
        run: echo "FLOW_TYPE=pull-request" >> $GITHUB_ENV
      - name: Set FLOW_TYPE to branch
        if: github.event_name == 'push'
        run: echo "FLOW_TYPE=branch" >> $GITHUB_ENV
      - name: Build Chain ${{ matrix.java-version }}
        id: build-chain
        uses: kiegroup/github-action-build-chain@feature/branch_flow
        with:
          definition-file: https://raw.githubusercontent.com/Ginxo/kogito-pipelines/fix/branch_flow/.ci/pull-request-config.yaml
          starting-project: kiegroup/optaplanner
          flow-type: ${{ env.FLOW_TYPE }}
      - name: Check Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1.0.10
        with:
          fail_on_test_failures: true
          fail_if_no_tests: false
          skip_publishing: true
          report_paths: '**/*-reports/TEST-*.xml'
